# Generated by Django 5.0.1 on 2024-02-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('map_longitude', models.CharField(max_length=32)),
                ('map_latitude', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=64)),
            ],
        ),
    ]
